server:
  port: 20250

spring:
  application:
    name: Campus-Hiking-AI
  main:
    allow-circular-references: true
  profiles:
    active: dev
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
#    druid:
      driver-class-name: ${co2.datasource.driver-class-name}
      url: jdbc:mysql://${co2.datasource.host}:${co2.datasource.port}/${co2.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${co2.datasource.username}
      password: ${co2.datasource.password}
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.com.campushikingai.domain
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

co2:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 设置jwt签名的密钥
    user-secret-key: absjdkafd
    user-ttl: 7200000
    user-token-name: authentication

logging:
  level:
    org:
      com:
        campushikingai:
          mapper: debug
          service: info
          controller: info
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    #operations-sorter: order
  api-docs:
    path: /v3/api-docs
knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: 你知道吗


